In [1]:
import numpy as np

In [2]:
np.array([1,3,6,8,6])

array([1, 3, 6, 8, 6])

In [3]:
np.array([12,67,45,33,28,94,0.5,4.5,73.5,.5,0.7])

array([12. , 67. , 45. , 33. , 28. , 94. ,  0.5,  4.5, 73.5,  0.5,  0.7])

In [4]:
np.array([12,57,93,34,75,49,False])

array([12, 57, 93, 34, 75, 49,  0])

In [5]:
np.array([12,54,34,45,92,46,'hello vikash yadav',])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav'],
      dtype='<U18')

In [6]:
np.array([12,54,34,45,92,46,'hello vikash yadav','hi','rao shab'])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav', 'hi',
       'rao shab'], dtype='<U18')

In [7]:
np.array([12,54,34,45,92,46,True])

array([12, 54, 34, 45, 92, 46,  1])

In [8]:
np.array([[12,36,46,78],[45,65,48],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87])],
      dtype=object)

In [9]:
np.array([[12,36,46,78],[45,65,48,34],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48, 34]), list([45, 78, 87])],
      dtype=object)

In [10]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [11]:
np.array([[12,36,46,78],[45,65,48,0],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48,  0],
       [45, 78, 87, 76]])

In [12]:
np.array([[12,36,46,78],[45,65,48],[45,78,87,76]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87, 76])],
      dtype=object)

In [13]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [18]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [19]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [20]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [22]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [23]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)

In [29]:
np.identity(1)

array([[1.]])

In [30]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
np.identity(5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [33]:
np.identity(5,dtype='float64')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
np.identity(5,dtype='float32')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [36]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
np.identity(5,dtype='float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.identity(5,dtype=np.str)
#queri here

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [39]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [40]:
np.ones(5,float)

array([1., 1., 1., 1., 1.])

In [41]:
np.ones(5,str)
#queri here

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [42]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.ones(1)

array([1.])

In [45]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [47]:
np.linspace(1,25, num=30, retstep=True)

(array([ 1.        ,  1.82758621,  2.65517241,  3.48275862,  4.31034483,
         5.13793103,  5.96551724,  6.79310345,  7.62068966,  8.44827586,
         9.27586207, 10.10344828, 10.93103448, 11.75862069, 12.5862069 ,
        13.4137931 , 14.24137931, 15.06896552, 15.89655172, 16.72413793,
        17.55172414, 18.37931034, 19.20689655, 20.03448276, 20.86206897,
        21.68965517, 22.51724138, 23.34482759, 24.17241379, 25.        ]),
 0.8275862068965517)

In [48]:
np.linspace(1,30, num=30,dtype=int,retstep=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 1.0)

In [49]:
np.linspace(1,30, num=30,retstep=True)
#queri true or flase

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30.]), 1.0)

In [50]:
np.random.random()
#will be random number genrated b/w 0 to 1

0.07932067791073372

In [51]:
np.random.random()

0.5498057754570426

In [52]:
np.random.random(5)

array([0.31751007, 0.11756959, 0.95898269, 0.09967176, 0.22190644])

In [53]:
np.random.random(2)
#queri here count spaces

array([0.22481026, 0.12827338])

In [54]:
np.random.random((1,1))

array([[0.03696977]])

In [55]:
np.random.random((1,7))

array([[0.71880419, 0.70746073, 0.77991168, 0.36386131, 0.22164134,
        0.92475422, 0.11307844]])

In [56]:
np.random.random((1,2))

array([[0.88099919, 0.10418338]])

In [57]:
np.random.random((1,23))

array([[0.7445675 , 0.422508  , 0.41361204, 0.02173848, 0.91477799,
        0.94165863, 0.91001007, 0.19626209, 0.83902858, 0.93854657,
        0.43813213, 0.25908713, 0.43985803, 0.65494943, 0.51826458,
        0.42977831, 0.48393511, 0.33153101, 0.44900954, 0.74735077,
        0.62477699, 0.54432722, 0.31759197]])

In [58]:
np.random.random((2,4))

array([[0.49473023, 0.24236277, 0.69045528, 0.07389524],
       [0.34946491, 0.90481581, 0.92419578, 0.21879576]])

In [59]:
np.random.random((5,5))

array([[0.54981929, 0.80078476, 0.47949464, 0.1626119 , 0.19975638],
       [0.52700073, 0.69868646, 0.93352278, 0.19920103, 0.66571223],
       [0.72219405, 0.12000832, 0.73557079, 0.05588314, 0.74459419],
       [0.88498714, 0.70091046, 0.04926647, 0.98326919, 0.22067497],
       [0.3740863 , 0.73462848, 0.80626575, 0.4333396 , 0.23151944]])

In [60]:
np.random.random((1,5))

array([[0.33680154, 0.04206559, 0.78032555, 0.62634501, 0.18245981]])

In [61]:
np.random.randn(5)

array([-0.06437901, -1.56188143, -0.72624798,  1.00254168, -0.90710639])

In [62]:
np.random.randn((2))

array([-0.64567614,  0.68344276])

In [63]:
np.abs(np.random.randn(5,1))

array([[1.07586978],
       [0.56504066],
       [0.3598151 ],
       [0.40877639],
       [1.01371001]])

In [64]:
np.abs(np.random.randn(1,5))

array([[0.1954853 , 2.03188982, 1.04327713, 0.67337384, 1.04559427]])

In [65]:
np.abs(np.random.randn(4))
#queri here -values do mod

array([0.39709515, 0.38109419, 0.59744233, 1.00005998])

In [66]:
np.abs(np.random.randn(5,1))

array([[0.72310945],
       [0.85083827],
       [0.89183351],
       [0.74190203],
       [1.92417336]])

In [67]:
np.abs(np.random.randn(5,2))
#abs for absalute values

array([[0.62097981, 0.03991677],
       [1.16140597, 0.54692909],
       [0.32415994, 0.40152888],
       [0.54737831, 0.9582879 ],
       [0.50358462, 0.34176677]])

In [68]:
np.abs(np.random.randn(5,3))

array([[0.76550192, 0.36869606, 1.29158492],
       [0.69109357, 1.1971043 , 1.24227502],
       [1.35854944, 0.44668767, 1.5621866 ],
       [0.06393762, 0.34756406, 1.77382735],
       [0.20584753, 0.25836234, 0.29420616]])

In [69]:
np.random.randint(1)
#queri here what is the work for randint

0

In [70]:
np.random.randint(2)
#queri here actual work for randint

0

In [71]:
np.random.randint(1,2)

1

In [72]:
np.random.randint(1,2)

1

In [73]:
np.random.randint(1,3)

1

In [74]:
np.random.randint(1,3)
np.random.randint(1,3)

1

In [75]:
np.random.randint(1,4)

3

In [76]:
np.random.randint(1,4)

3

In [77]:
np.random.randint(1,4)

1

In [78]:
np.random.randint(1,4)

3

In [79]:
np.random.randint(1,4)

2

In [80]:
np.random.randint(1,100,50)

array([16, 99, 32, 15,  2, 26, 14, 93, 44, 96, 54, 69, 39, 75,  1, 14, 58,
       77, 76, 81, 51, 84, 90, 33, 92, 94, 73, 43, 99, 78, 19, 10,  1,  1,
       25, 17, 72, 16, 70, 83, 57, 67, 84, 35, 45, 66, 79, 43, 97, 47])

In [81]:
np.random.randint(0,100,2)
#queri here i want 2*multiple number only

array([72, 99])

In [82]:
np.random.randint(1,100)

45

In [83]:
np.random.randint(1,100)

2

In [84]:
np.random.randint(1,100)
#queri here probability for one number repeat again and again

89

In [85]:
np.random.randint(1,100,1)

array([19])

In [86]:
np.random.randint(1,100,25)

array([76, 83, 85, 64, 27,  7, 84, 25, 15, 61, 55, 20, 94,  6, 96, 86, 81,
       98, 14, 98, 67, 60, 57, 80, 28])

In [87]:
np.random.randint(1,10,10)

array([4, 3, 2, 2, 7, 5, 7, 3, 9, 4])

In [88]:
np.random.randint(1,100,(5,5,(10)))

array([[[65, 58, 43, 22,  3, 37, 73, 26, 66, 14],
        [78, 80, 82, 21, 42, 54, 61, 98, 86, 62],
        [31, 91, 69, 20, 94, 87, 96, 86, 44, 55],
        [76, 96, 30, 57, 96, 69,  9, 11, 86, 84],
        [37, 80, 34, 25, 60, 58, 41,  7, 34, 98]],

       [[77,  3, 63,  5, 85, 34, 44, 26, 13, 79],
        [69, 77, 23, 39, 13, 64, 40,  2, 43, 81],
        [94, 62, 24, 52, 99, 84,  6, 23, 76, 44],
        [69, 36,  1, 14, 44, 95, 71, 47, 74, 34],
        [78, 28, 53, 58, 13, 95, 73, 80, 64, 93]],

       [[69, 72, 87,  7,  6, 79, 23, 10, 21,  9],
        [51, 37, 45, 71, 99, 83,  5, 84, 54, 89],
        [21, 91, 91, 41, 50, 90, 38, 48, 24, 58],
        [86, 30, 94, 73, 43, 47, 28, 80, 33,  1],
        [57, 31, 55, 96, 66, 29, 95, 11, 61, 10]],

       [[81, 28, 23, 89, 97, 29, 13, 69, 73,  8],
        [46, 81, 17,  4,  4, 64, 32, 64, 25, 77],
        [24, 93, 80,  9, 73, 21, 60, 29, 50, 74],
        [20, 95, 75, 97, 52,  6, 17, 60,  5, 64],
        [37, 26, 62, 22, 70, 63, 15, 46, 63,

In [89]:
np.random.randint(1,100,(1,5))

array([[99, 35, 62, 92, 84]])

In [90]:
np.random.randint(1,100,(2,5))

array([[43,  4, 19, 73, 14],
       [50, 72, 50, 84,  2]])

In [91]:
np.random.randint(1,100,(2,2))

array([[94, 54],
       [11, 69]])

In [92]:
np.random.randint(1,100,(4,5))

array([[79, 15, 41, 14, 20],
       [40, 17, 94, 73, 26],
       [72, 34, 83, 83, 49],
       [82, 42, 76, 93, 15]])

In [93]:
np.random.randint(1,100,(4,6))

array([[85, 47,  5, 57,  2, 89],
       [77, 43, 69, 65, 12, 54],
       [ 6, 12, 55, 60, 88, 60],
       [61, 55, 22, 33, 43, 80]])

In [94]:
x=np.random.randint(1,10,(5))

In [95]:
x

array([9, 3, 6, 2, 3])

In [96]:
np.shape(x)
#queri here what is the shape

(5,)

In [97]:
len(x)
#queri here for len related to numpy

5

In [98]:
len(x)

5

In [99]:
x=np.random.randint(1,10,(5,4))

In [100]:
x

array([[8, 8, 7, 5],
       [4, 4, 5, 4],
       [4, 1, 1, 6],
       [4, 7, 7, 5],
       [5, 8, 1, 1]])

In [101]:
np.shape(x)

(5, 4)

In [102]:
x=np.random.randint(1,10,(5,5))

In [103]:
x

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6],
       [3, 8, 2, 8, 7]])

In [104]:
np.shape(x)

(5, 5)

In [105]:
len(x)

5

In [106]:
x[0]
#queri here x[index]

array([8, 2, 4, 2, 5])

In [107]:
x[1]

array([1, 6, 6, 3, 9])

In [108]:
x[4]

array([3, 8, 2, 8, 7])

In [109]:
x[-1]

array([3, 8, 2, 8, 7])

In [110]:
x[-2]

array([3, 9, 1, 1, 6])

In [111]:
x[-5]

array([8, 2, 4, 2, 5])

In [112]:
x[0:26]
#queri here after : what is work for number

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6],
       [3, 8, 2, 8, 7]])

In [113]:
x[0:4]

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6]])

In [114]:
x[0:1]

array([[8, 2, 4, 2, 5]])

In [115]:
x[0:2]

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9]])

In [116]:
x[0:-1]
#queri here -1 not follow the rules

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6]])

In [117]:
x[0:-2]

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9]])

In [118]:
x[0:0]

array([], shape=(0, 5), dtype=int32)

In [119]:
x[::-1]

array([[3, 8, 2, 8, 7],
       [3, 9, 1, 1, 6],
       [5, 2, 1, 7, 9],
       [1, 6, 6, 3, 9],
       [8, 2, 4, 2, 5]])

In [120]:
x[10:0:-1]
#what is the for 10 here

array([[3, 8, 2, 8, 7],
       [3, 9, 1, 1, 6],
       [5, 2, 1, 7, 9],
       [1, 6, 6, 3, 9]])

In [121]:
x[10:0:-2]
#queri only for - index

array([[3, 8, 2, 8, 7],
       [5, 2, 1, 7, 9]])

In [122]:
x[10:0:-3]
#queri only for - index

array([[3, 8, 2, 8, 7],
       [1, 6, 6, 3, 9]])

In [123]:
x[0:0:-1]

array([], shape=(0, 5), dtype=int32)

In [124]:
x[::-1]

array([[3, 8, 2, 8, 7],
       [3, 9, 1, 1, 6],
       [5, 2, 1, 7, 9],
       [1, 6, 6, 3, 9],
       [8, 2, 4, 2, 5]])

In [125]:
x[::5]

array([[8, 2, 4, 2, 5]])

In [126]:
x[::4]

array([[8, 2, 4, 2, 5],
       [3, 8, 2, 8, 7]])

In [127]:
x[::1]

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6],
       [3, 8, 2, 8, 7]])

In [128]:
x[10:0:1]

array([], shape=(0, 5), dtype=int32)

In [129]:
#new matrix here data calculate

In [130]:
y=np.random.randint(1,50,(5,5))

In [131]:
y[0]

array([17, 22, 48, 46, 31])

In [132]:
y[0][0]

17

In [133]:
y[0][4]

31

In [134]:
y[0][-1]

31

In [135]:
y[0:5]

array([[17, 22, 48, 46, 31],
       [41, 23, 24, 19, 29],
       [40, 22, 15, 14,  4],
       [29, 11,  3,  4, 12],
       [38, 27,  7,  1, 40]])

In [136]:
y[0:4]

array([[17, 22, 48, 46, 31],
       [41, 23, 24, 19, 29],
       [40, 22, 15, 14,  4],
       [29, 11,  3,  4, 12]])

In [137]:
y[0:-1]

array([[17, 22, 48, 46, 31],
       [41, 23, 24, 19, 29],
       [40, 22, 15, 14,  4],
       [29, 11,  3,  4, 12]])

In [138]:
y[:,2:4]
#here 2:4 means index [2] to [4-1] print columns
#here first : is row senoted

array([[48, 46],
       [24, 19],
       [15, 14],
       [ 3,  4],
       [ 7,  1]])

In [139]:
y[:,2:5]

array([[48, 46, 31],
       [24, 19, 29],
       [15, 14,  4],
       [ 3,  4, 12],
       [ 7,  1, 40]])

In [140]:
y[0:3,2:5]
#here [0] to [3-1] to print row wise data

array([[48, 46, 31],
       [24, 19, 29],
       [15, 14,  4]])

In [141]:
y+x

array([[25, 24, 52, 48, 36],
       [42, 29, 30, 22, 38],
       [45, 24, 16, 21, 13],
       [32, 20,  4,  5, 18],
       [41, 35,  9,  9, 47]])

In [142]:
x

array([[8, 2, 4, 2, 5],
       [1, 6, 6, 3, 9],
       [5, 2, 1, 7, 9],
       [3, 9, 1, 1, 6],
       [3, 8, 2, 8, 7]])

In [143]:
y

array([[17, 22, 48, 46, 31],
       [41, 23, 24, 19, 29],
       [40, 22, 15, 14,  4],
       [29, 11,  3,  4, 12],
       [38, 27,  7,  1, 40]])

In [144]:
y=y+x

In [145]:
y

array([[25, 24, 52, 48, 36],
       [42, 29, 30, 22, 38],
       [45, 24, 16, 21, 13],
       [32, 20,  4,  5, 18],
       [41, 35,  9,  9, 47]])