In [2]:
import numpy as np

In [3]:
np.array([1,3,6,8,6])

array([1, 3, 6, 8, 6])

In [4]:
np.array([12,67,45,33,28,94,0.5,4.5,73.5,.5,0.7])

array([12. , 67. , 45. , 33. , 28. , 94. ,  0.5,  4.5, 73.5,  0.5,  0.7])

In [5]:
np.array([12,57,93,34,75,49,False])

array([12, 57, 93, 34, 75, 49,  0])

In [6]:
np.array([12,54,34,45,92,46,'hello vikash yadav',])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav'],
      dtype='<U18')

In [7]:
np.array([12,54,34,45,92,46,'hello vikash yadav','hi','rao shab'])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav', 'hi',
       'rao shab'], dtype='<U18')

In [8]:
np.array([12,54,34,45,92,46,True])

array([12, 54, 34, 45, 92, 46,  1])

In [9]:
np.array([[12,36,46,78],[45,65,48],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87])],
      dtype=object)

In [10]:
np.array([[12,36,46,78],[45,65,48,34],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48, 34]), list([45, 78, 87])],
      dtype=object)

In [11]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [12]:
np.array([[12,36,46,78],[45,65,48,0],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48,  0],
       [45, 78, 87, 76]])

In [13]:
np.array([[12,36,46,78],[45,65,48],[45,78,87,76]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87, 76])],
      dtype=object)

In [14]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [19]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [21]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [23]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [24]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [26]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)

In [30]:
np.identity(1)

array([[1.]])

In [31]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.identity(5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [34]:
np.identity(5,dtype='float64')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.identity(5,dtype='float32')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [37]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
np.identity(5,dtype='float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.identity(5,dtype='char')
#queri here

TypeError: data type "char" not understood

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [41]:
np.ones(5,float)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones(5,'char')
#queri here

TypeError: data type "char" not understood

In [45]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.ones(1)

array([1.])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [50]:
np.linspace(1,25, num=30, retstep=True)

(array([ 1.        ,  1.82758621,  2.65517241,  3.48275862,  4.31034483,
         5.13793103,  5.96551724,  6.79310345,  7.62068966,  8.44827586,
         9.27586207, 10.10344828, 10.93103448, 11.75862069, 12.5862069 ,
        13.4137931 , 14.24137931, 15.06896552, 15.89655172, 16.72413793,
        17.55172414, 18.37931034, 19.20689655, 20.03448276, 20.86206897,
        21.68965517, 22.51724138, 23.34482759, 24.17241379, 25.        ]),
 0.8275862068965517)

In [57]:
np.linspace(1,30, num=30,dtype=int,retstep=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 1.0)

In [69]:
np.linspace(1,30, num=30,retstep=True)
#queri true or flase

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30.]), 1.0)

In [60]:
np.random.random()
#will be random number genrated b/w 0 to 1

0.32611474539067165

In [61]:
np.random.random()

0.12967616998599008

In [65]:
np.random.random(5)

array([0.43069038, 0.0413129 , 0.01098592, 0.89206619, 0.45351287])

In [68]:
np.random.random(2,retstep=True)
#queri here count spaces

TypeError: random_sample() got an unexpected keyword argument 'retstep'

In [70]:
np.random.random((1,1))

array([[0.78966654]])

In [71]:
np.random.random((0,1))

array([], shape=(0, 1), dtype=float64)

In [72]:
np.random.random((1,2))

array([[0.02105545, 0.88231183]])