In [1]:
import numpy as np

In [3]:
np.array([1,3,6,8,6])

array([1, 3, 6, 8, 6])

In [4]:
np.array([12,67,45,33,28,94,0.5,4.5,73.5,.5,0.7])

array([12. , 67. , 45. , 33. , 28. , 94. ,  0.5,  4.5, 73.5,  0.5,  0.7])

In [5]:
np.array([12,57,93,34,75,49,False])

array([12, 57, 93, 34, 75, 49,  0])

In [6]:
np.array([12,54,34,45,92,46,'hello vikash yadav',])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav'],
      dtype='<U18')

In [7]:
np.array([12,54,34,45,92,46,'hello vikash yadav','hi','rao shab'])

array(['12', '54', '34', '45', '92', '46', 'hello vikash yadav', 'hi',
       'rao shab'], dtype='<U18')

In [8]:
np.array([12,54,34,45,92,46,True])

array([12, 54, 34, 45, 92, 46,  1])

In [9]:
np.array([[12,36,46,78],[45,65,48],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87])],
      dtype=object)

In [10]:
np.array([[12,36,46,78],[45,65,48,34],[45,78,87]])

array([list([12, 36, 46, 78]), list([45, 65, 48, 34]), list([45, 78, 87])],
      dtype=object)

In [11]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [12]:
np.array([[12,36,46,78],[45,65,48,0],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48,  0],
       [45, 78, 87, 76]])

In [13]:
np.array([[12,36,46,78],[45,65,48],[45,78,87,76]])

array([list([12, 36, 46, 78]), list([45, 65, 48]), list([45, 78, 87, 76])],
      dtype=object)

In [14]:
np.array([[12,36,46,78],[45,65,48,35],[45,78,87,76]])

array([[12, 36, 46, 78],
       [45, 65, 48, 35],
       [45, 78, 87, 76]])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [19]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [21]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [23]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [24]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [26]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)

In [30]:
np.identity(1)

array([[1.]])

In [31]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.identity(5,dtype='int64')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [34]:
np.identity(5,dtype='float64')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.identity(5,dtype='float32')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [37]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
np.identity(5,dtype='float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.identity(5,dtype='char')
#queri here

TypeError: data type "char" not understood

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [41]:
np.ones(5,float)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones(5,'char')
#queri here

TypeError: data type "char" not understood

In [45]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.ones(1)

array([1.])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [50]:
np.linspace(1,25, num=30, retstep=True)

(array([ 1.        ,  1.82758621,  2.65517241,  3.48275862,  4.31034483,
         5.13793103,  5.96551724,  6.79310345,  7.62068966,  8.44827586,
         9.27586207, 10.10344828, 10.93103448, 11.75862069, 12.5862069 ,
        13.4137931 , 14.24137931, 15.06896552, 15.89655172, 16.72413793,
        17.55172414, 18.37931034, 19.20689655, 20.03448276, 20.86206897,
        21.68965517, 22.51724138, 23.34482759, 24.17241379, 25.        ]),
 0.8275862068965517)

In [57]:
np.linspace(1,30, num=30,dtype=int,retstep=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 1.0)

In [69]:
np.linspace(1,30, num=30,retstep=True)
#queri true or flase

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30.]), 1.0)

In [60]:
np.random.random()
#will be random number genrated b/w 0 to 1

0.32611474539067165

In [61]:
np.random.random()

0.12967616998599008

In [65]:
np.random.random(5)

array([0.43069038, 0.0413129 , 0.01098592, 0.89206619, 0.45351287])

In [68]:
np.random.random(2,retstep=True)
#queri here count spaces

TypeError: random_sample() got an unexpected keyword argument 'retstep'

In [70]:
np.random.random((1,1))

array([[0.78966654]])

In [71]:
np.random.random((0,1))

array([], shape=(0, 1), dtype=float64)

In [2]:
np.random.random((1,2))

array([[0.72386132, 0.69590463]])

In [3]:
np.random.random((1,23))

array([[0.65960014, 0.84701784, 0.72387574, 0.53082393, 0.26874473,
        0.95421693, 0.95026731, 0.65382813, 0.22547318, 0.99786687,
        0.50084512, 0.36587172, 0.06780143, 0.51706861, 0.87501691,
        0.72631172, 0.99956193, 0.53668327, 0.05009079, 0.24244275,
        0.24385106, 0.46123133, 0.61997961]])

In [4]:
np.random.random((2,4))

array([[0.31581944, 0.5341259 , 0.91060788, 0.87875016],
       [0.7373235 , 0.4870872 , 0.06854937, 0.90908811]])

In [5]:
np.random.random((5,5))

array([[0.22827901, 0.91463401, 0.45799263, 0.86244221, 0.49046162],
       [0.83127589, 0.69563102, 0.93896637, 0.8654029 , 0.99475239],
       [0.88455176, 0.3057491 , 0.86660717, 0.60297815, 0.78115949],
       [0.34962518, 0.24314092, 0.16614133, 0.0798558 , 0.74293433],
       [0.00888404, 0.27344379, 0.6663144 , 0.06668361, 0.59430054]])

In [6]:
np.random.random((1,5))

array([[0.10731339, 0.41495088, 0.24233865, 0.12212036, 0.96190396]])

In [7]:
np.random.randn(5)

array([-1.51106733,  1.25736293,  0.6856658 , -0.63138822, -1.45610033])

In [8]:
np.random.randn(0)

array([], dtype=float64)

In [9]:
np.random.randn(5)

array([ 1.10443822, -0.53375303, -1.70595011,  0.01317445, -0.36105623])

In [10]:
np.random.randn(5)

array([-0.78555697,  0.63302444, -0.43440686,  0.04299319,  0.03123237])

In [11]:
np.random.randn(4)
#queri here -values do mod

array([-0.83507426,  0.0967276 ,  0.59174824,  0.0724406 ])

In [12]:
np.random.randn(5,1)

array([[-0.19304457],
       [ 0.4550047 ],
       [-0.68630209],
       [ 0.76917134],
       [ 0.01365165]])

In [13]:
np.random.randn(5,2)

array([[-1.23207045,  0.7752329 ],
       [ 1.51184974,  0.71623688],
       [-0.03473244, -0.99723652],
       [ 1.17067827, -0.04030369],
       [-0.96588987, -1.63857297]])

In [14]:
np.random.randn(5,3)

array([[ 0.94252407,  1.37014059,  0.71874528],
       [-0.07889359, -0.0101973 ,  0.44373941],
       [-0.44670224, -0.29475644,  0.75784341],
       [ 1.23486484, -1.1980379 , -0.8871359 ],
       [ 2.23247719,  0.26756996,  1.19348718]])

In [16]:
np.random.randint(1)
#queri here what is the work for randint

0

In [17]:
np.random.randint(2)
#queri here actual work for randint

0

In [18]:
np.random.randint(1,2)

1

In [19]:
np.random.randint(1,2)

1

In [20]:
np.random.randint(1,3)

2

In [21]:
np.random.randint(1,3)
np.random.randint(1,3)

2

In [22]:
np.random.randint(1,4)

1

In [23]:
np.random.randint(1,4)

1

In [24]:
np.random.randint(1,4)

2

In [25]:
np.random.randint(1,4)

2

In [26]:
np.random.randint(1,4)

1

In [27]:
np.random.randint(1,100)

87

In [28]:
np.random.randint(1,100)

43

In [29]:
np.random.randint(1,100)

42

In [30]:
np.random.randint(1,100)

79

In [31]:
np.random.randint(1,100)
#queri here probability for one number repeat again and again

51

In [32]:
np.random.randint(1,100,1)

array([55])

In [33]:
np.random.randint(1,100,25)

array([93, 69, 89, 49, 49, 63, 67, 57, 52, 14,  7, 90, 84, 98, 58, 61,  9,
       55, 39, 96, 16, 63, 25, 39, 80])

In [34]:
np.random.randint(1,10,10)

array([3, 3, 8, 3, 6, 4, 9, 8, 3, 9])

In [35]:
np.random.randint(1,100,10)

array([68,  7, 85, 51, 97, 55, 19, 17,  3, 26])

In [36]:
np.random.randint(1,100,(1,5))

array([[30, 55, 93, 31, 17]])

In [37]:
np.random.randint(1,100,(2,5))

array([[32, 40, 61, 83, 81],
       [86, 25, 44, 50, 39]])

In [38]:
np.random.randint(1,100,(2,2))

array([[29,  6],
       [13,  1]])

In [39]:
np.random.randint(1,100,(4,5))

array([[83, 55, 95, 62,  7],
       [ 6,  8, 48, 99, 23],
       [62, 79, 72, 41, 30],
       [44, 59, 33, 61,  7]])

In [40]:
np.random.randint(1,100,(4,6))

array([[42,  3, 92, 29, 26, 94],
       [93,  7,  9, 86, 17, 77],
       [57, 33, 43, 87, 22, 91],
       [94, 31, 19, 65, 40, 81]])

In [41]:
x=np.random.randint(1,10,5)

In [42]:
x

array([9, 3, 3, 8, 2])

In [43]:
np.shape(x)
#queri here what is the shape

(5,)

In [44]:
np.len(x)
#queri here for len related to numpy

AttributeError: module 'numpy' has no attribute 'len'

In [45]:
len(x)

5

In [46]:
x=np.random.randint(1,10,(5,4))

In [47]:
x

array([[5, 3, 7, 4],
       [4, 9, 8, 6],
       [2, 5, 1, 7],
       [5, 5, 9, 4],
       [3, 3, 5, 1]])

In [49]:
np.shape(x)

(5, 4)

In [50]:
x=np.random.randint(1,10,5)

In [51]:
x

array([5, 6, 7, 8, 5])

In [52]:
np.shape(x)

(5,)

In [53]:
len(x)

5

In [54]:
x[0]
#queri here x[index]

5

In [55]:
x[1]

6

In [57]:
x[4]

5

In [58]:
x[-1]

5

In [59]:
x[-2]

8

In [60]:
x[-5]

5

In [61]:
x[0:5]

array([5, 6, 7, 8, 5])

In [62]:
x[0:4]

array([5, 6, 7, 8])

In [63]:
x[0:1]

array([5])

In [64]:
x[0:2]

array([5, 6])

In [65]:
x[0:-1]
#queri here -1 not follow the rules

array([5, 6, 7, 8])

In [66]:
x[0:-2]

array([5, 6, 7])

In [67]:
x[0:0]

array([], dtype=int32)

In [68]:
x[10:0:-1]

array([5, 8, 7, 6])

In [72]:
x[10:0:-3]
#queri only for - index

array([5, 6])

In [73]:
x[0:0:-1]

array([], dtype=int32)

In [74]:
x[::-1]

array([5, 8, 7, 6, 5])

In [75]:
x[::5]

array([5])

In [76]:
x[::4]

array([5, 5])

In [78]:
x[::1]

array([5, 6, 7, 8, 5])

In [79]:
x[10:0:1]

array([], dtype=int32)