In [1]:
 import numpy as np

In [2]:
x=np.random.randint(1,50,25)

In [3]:
x

array([11, 23,  4,  7, 42, 36, 45, 38, 18, 16, 38, 41, 15, 12,  8,  8, 19,
       32,  7, 12, 29, 31, 45, 14, 46])

In [5]:
np.sum(x)

597

In [6]:
x.sum()

597

In [8]:
np.max(x)

46

In [9]:
x.max()

46

In [10]:
np.min(x)

4

In [11]:
x.min()

4

In [12]:
np.mean(x)

23.88

In [13]:
x.mean()

23.88

In [14]:
np.var(x)

196.26559999999998

In [15]:
x.var()

196.26559999999998

In [16]:
np.median(x)

19.0

In [21]:
np.median(x)
#not working x.median()

19.0

In [22]:
np.std(x)

14.009482502933503

In [23]:
x.std()

14.009482502933503

In [24]:
np.sort(x)

array([ 4,  7,  7,  8,  8, 11, 12, 12, 14, 15, 16, 18, 19, 23, 29, 31, 32,
       36, 38, 38, 41, 42, 45, 45, 46])

In [26]:
x.sort()

In [27]:
x

array([ 4,  7,  7,  8,  8, 11, 12, 12, 14, 15, 16, 18, 19, 23, 29, 31, 32,
       36, 38, 38, 41, 42, 45, 45, 46])

In [28]:
x.argmax()
#index of element of maximum number

24

In [29]:
np.argmax(x)

24

In [30]:
x.argmin()

0

In [31]:
np.argmin(x)

0

In [37]:
x.reshape(5,5)
#reshape convert 1D to 2D array

array([[ 4,  7,  7,  8,  8],
       [11, 12, 12, 14, 15],
       [16, 18, 19, 23, 29],
       [31, 32, 36, 38, 38],
       [41, 42, 45, 45, 46]])

In [38]:
np.reshape(x,(5,5))

array([[ 4,  7,  7,  8,  8],
       [11, 12, 12, 14, 15],
       [16, 18, 19, 23, 29],
       [31, 32, 36, 38, 38],
       [41, 42, 45, 45, 46]])

In [39]:
np.reshape(x,(5,-1))

array([[ 4,  7,  7,  8,  8],
       [11, 12, 12, 14, 15],
       [16, 18, 19, 23, 29],
       [31, 32, 36, 38, 38],
       [41, 42, 45, 45, 46]])

In [40]:
np.reshape(x,(5,-2))

array([[ 4,  7,  7,  8,  8],
       [11, 12, 12, 14, 15],
       [16, 18, 19, 23, 29],
       [31, 32, 36, 38, 38],
       [41, 42, 45, 45, 46]])

In [41]:
np.reshape(x,(-1,5))

array([[ 4,  7,  7,  8,  8],
       [11, 12, 12, 14, 15],
       [16, 18, 19, 23, 29],
       [31, 32, 36, 38, 38],
       [41, 42, 45, 45, 46]])

In [46]:
np.reshape(x,(-1,4))

array([[15, 36,  1, 43],
       [15, 36, 35, 37],
       [13, 47, 35,  4],
       [10,  1, 33, 49],
       [ 6, 24, 14, 45],
       [37,  8, 36, 21]])

In [43]:
x=np.random.randint(1,50,24)

In [44]:
x

array([15, 36,  1, 43, 15, 36, 35, 37, 13, 47, 35,  4, 10,  1, 33, 49,  6,
       24, 14, 45, 37,  8, 36, 21])

In [47]:
np.reshape(x,(6,-1))

array([[15, 36,  1, 43],
       [15, 36, 35, 37],
       [13, 47, 35,  4],
       [10,  1, 33, 49],
       [ 6, 24, 14, 45],
       [37,  8, 36, 21]])

In [48]:
np.reshape(x,(-1,3))

array([[15, 36,  1],
       [43, 15, 36],
       [35, 37, 13],
       [47, 35,  4],
       [10,  1, 33],
       [49,  6, 24],
       [14, 45, 37],
       [ 8, 36, 21]])

In [49]:
x=np.reshape(x,(4,6))

In [50]:
x

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21]])

In [51]:
np.sum(x)

601

In [52]:
np.sum(x,axis=0)
#axis [0] columns wise sum

array([ 74, 119,  84, 147,  92,  85])

In [53]:
np.sum(x,axis=1)
#axis [1] row wise sum

array([146, 171, 123, 161])

In [54]:
np.max(x,axis=0)

array([35, 45, 37, 49, 36, 36])

In [55]:
np.max(x,axis=1)

array([43, 47, 49, 45])

In [60]:
#np.flatten(x) not working
x.flatten()
#convert n Dimentions to 1D

array([15, 36,  1, 43, 15, 36, 35, 37, 13, 47, 35,  4, 10,  1, 33, 49,  6,
       24, 14, 45, 37,  8, 36, 21])

In [61]:
x

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21]])

In [63]:
np.vstack(x)

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21]])

In [64]:
np.hstack(x)

array([15, 36,  1, 43, 15, 36, 35, 37, 13, 47, 35,  4, 10,  1, 33, 49,  6,
       24, 14, 45, 37,  8, 36, 21])

In [65]:
x1=np.array([[4,2,4,1,6,8]])
x2=np.array([[45],[105],[48],[96]])

In [68]:
np.hstack((x, x2))
#if you add a new columns

array([[ 15,  36,   1,  43,  15,  36,  45],
       [ 35,  37,  13,  47,  35,   4, 105],
       [ 10,   1,  33,  49,   6,  24,  48],
       [ 14,  45,  37,   8,  36,  21,  96]])

In [69]:
np.vstack((x,x1))
#if you add a new row 

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21],
       [ 4,  2,  4,  1,  6,  8]])

In [71]:
np.r_[x,x1]

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21],
       [ 4,  2,  4,  1,  6,  8]])

In [72]:
np.c_[x,x2]

array([[ 15,  36,   1,  43,  15,  36,  45],
       [ 35,  37,  13,  47,  35,   4, 105],
       [ 10,   1,  33,  49,   6,  24,  48],
       [ 14,  45,  37,   8,  36,  21,  96]])

In [73]:
x

array([[15, 36,  1, 43, 15, 36],
       [35, 37, 13, 47, 35,  4],
       [10,  1, 33, 49,  6, 24],
       [14, 45, 37,  8, 36, 21]])

In [74]:
np.where(x<10)

(array([0, 1, 2, 2, 3], dtype=int64), array([2, 5, 1, 4, 3], dtype=int64))

In [76]:
np.where(x<10,x-5,x)

array([[15, 36, -4, 43, 15, 36],
       [35, 37, 13, 47, 35, -1],
       [10, -4, 33, 49,  1, 24],
       [14, 45, 37,  3, 36, 21]])

In [77]:
np.where(x<10,x+5,x)

array([[15, 36,  6, 43, 15, 36],
       [35, 37, 13, 47, 35,  9],
       [10,  6, 33, 49, 11, 24],
       [14, 45, 37, 13, 36, 21]])